### ISSUE TITLE
Implement pre-commit for webpack bundles

### ISSUE THREAD

**Issue by maltezacharias** [Baschdl/match4healthcare#464]
- [ ] Automatically run prettier on build
- [ ] Automatic linting 
- [ ] Prevent committing as long as linting errors exist
- [ ] Document setup process for pre-commit hook on dev workstations

**Comment by bjrne** [comment]
From the config, setup seems rather easy with the pre-commit framework. i can give this a try tomorrow.

```yaml
- repo: https://github.com/prettier/prettier
  rev: "" # Use the sha or tag you want to point at
  hooks:
    - id: prettier
```
